function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 22-Jun-2023 08:28:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Data Points','Marker','o','LineStyle','none');

% Create plot
plot(X2,Y2,'DisplayName','Line of best fit, y =a_{0} +a_{1} x',...
    'LineWidth',2,...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create ylabel
ylabel('y','FontName','Times New Roman');

% Create xlabel
xlabel('x','FontName','Times New Roman');

% Create title
title('Linear Curve Fitting (Lease Square Method)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 3.4]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 16]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.151562770157979 0.733894018171888 0.369120654396728 0.141304347826087]);

% Create textbox
annotation(figure1,'textbox',...
    [0.50171769481816 0.648106904231624 0.0585361716857045 0.042147925622831],...
    'String','Error',...
    'FontSize',14,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create arrow
annotation(figure1,'arrow',[0.813241010689991 0.813194444444445],...
    [0.734181429644907 0.812513378141187],'Color',[1 0 0]);

% Create arrow
annotation(figure1,'arrow',[0.585585585585586 0.586805555555556],...
    [0.70774647887324 0.618466115844],'Color',[1 0 0]);

% Create arrow
annotation(figure1,'arrow',[0.358558558558559 0.358333333333333],...
    [0.47887323943662 0.419303052356693],'Color',[1 0 0],'HeadWidth',7,...
    'HeadStyle','cback2');

% Create arrow
annotation(figure1,'arrow',[0.220879899578879 0.223423423423423],...
    [0.201560170173183 0.27112676056338],'Color',[1 0 0]);

